### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/tomcat/util/log/SystemLogHandler

### ISSUE THREAD

**Issue by nuwanchamara** [cmoro-deusto/docker-tomcat8#6]
I got a error after i run the docker image on Mac high sierra

`java.lang.NoClassDefFoundError: org/apache/tomcat/util/log/SystemLogHandler
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.apache.catalina.startup.Bootstrap.init(Bootstrap.java:266)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:453)
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.util.log.SystemLogHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more`

Earlier versions worked without any problem. But Now i am getting a above error.

**Comment by cmoro-deusto** [comment]
Hi @nuwanchamara 

It works OK here. What's the docker command you are using to launch it?

**Comment by nuwanchamara** [comment]
First i used follwing command

`sudo docker run -d -p 8080:8080 -p 8009:8009 -v /Users/TMac/projects/VServer/docker/docker_dev/directories:/opt/tomcat/webapps dordoka/tomcat`

After that i used following command to run the image

`docekr run <imageID>`

**Comment by cmoro-deusto** [comment]
With the first command, you should be OK, providing you have a properly packaged application in your `/Users/TMac/projects/VServer/docker/docker_dev/directories`. Second command, if first is run, is not necesary.

I'm afraid the problem might be related to your application.

If you run the container without volumes:

```
docker run -d -p 8080:8080 -p 8009:8009
```
And then access the Tomcat Manager (login with admin/admin):
```
https://localhost:8080/manager
```
It should work. If it does, container should be OK.

Try and deploy your app using the manager to see if it starts correctly. Please come back with your results!

**Comment by nuwanchamara** [comment]
Container is not running . After i executed following command

`docker run -d -p 8080:8080 -p 8009:8009 dordoka/tomcat`

**Comment by cmoro-deusto** [comment]
I deleted all my local container cache and run:
```
docker run -d -p 8080:8080 -p 8009:8009 dordoka/tomcat
```
The container image was downloaded from docker hub and started OK.
```
 ~  docker run -d -p 8080:8080 -p 8089:8089 dordoka/tomcat                                                                 257ms  Thu 08 Feb 2018 06:48:38 CET
Unable to find image 'dordoka/tomcat:latest' locally
latest: Pulling from dordoka/tomcat
c954d15f947c: Pull complete 
c3688624ef2b: Pull complete 
848fe4263b3b: Pull complete 
23b4459d3b04: Pull complete 
36ab3b56c8f1: Pull complete 
55f07125e6de: Pull complete 
fbc0d8b919be: Pull complete 
369019843a9b: Pull complete 
71596e0f889e: Pull complete 
b2b1394140dc: Pull complete 
79ab17d2c5c1: Pull complete 
Digest: sha256:ab5cd7cd308fbf6f4d3c493a7d61aeb44aee9bf2e7c14ab989403bf077e27d45
Status: Downloaded newer image for dordoka/tomcat:latest
e5215b62ae3157d4b015e62bdb5490e0efcb51ae06e0d9ed5ea65d3c502f091b
 ~  docker logs -f e5215b62ae3157d4b015e62bdb5490e0efcb51ae06e0d9ed5ea65d3c502f091b                                        20.1s  Thu 08 Feb 2018 06:49:09 CET
08-Feb-2018 05:49:02.330 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.49
08-Feb-2018 05:49:02.331 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jan 19 2018 20:21:23 UTC
08-Feb-2018 05:49:02.331 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.49.0
08-Feb-2018 05:49:02.331 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.14.16-1-MANJARO
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-oracle/jre
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_161-b12
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/tomcat
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/tomcat
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
08-Feb-2018 05:49:02.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
08-Feb-2018 05:49:02.333 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
08-Feb-2018 05:49:02.333 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
08-Feb-2018 05:49:02.333 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat
08-Feb-2018 05:49:02.333 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat
08-Feb-2018 05:49:02.333 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
08-Feb-2018 05:49:02.333 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
08-Feb-2018 05:49:02.414 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
08-Feb-2018 05:49:02.421 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
08-Feb-2018 05:49:02.422 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
08-Feb-2018 05:49:02.423 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
08-Feb-2018 05:49:02.423 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 320 ms
08-Feb-2018 05:49:02.437 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
08-Feb-2018 05:49:02.437 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.49
08-Feb-2018 05:49:02.442 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /opt/tomcat/webapps/host-manager
08-Feb-2018 05:49:02.616 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /opt/tomcat/webapps/host-manager has finished in 173 ms
08-Feb-2018 05:49:02.616 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /opt/tomcat/webapps/manager
08-Feb-2018 05:49:02.633 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /opt/tomcat/webapps/manager has finished in 17 ms
08-Feb-2018 05:49:02.635 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
08-Feb-2018 05:49:02.639 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
08-Feb-2018 05:49:02.641 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 218 ms
```
Logged in to manager, deployed and app... works.

Please use [asciinema](https://asciinema.org/) to record the whole processs you follow and paste the link here to see if I can help.

**Comment by nuwanchamara** [comment]
i have reset the docker from  Preference > Reset . Now tomcat container working.

**Comment by cmoro-deusto** [comment]
Hi @nuwanchamara I'm glad you got it working!
Thanks for coming back with the solution.

Happy hacking!

**Comment by nuwanchamara** [comment]
Thanks for the early reply.
